### ISSUE TITLE
script doesn't read 0

### ISSUE THREAD

**Issue by shoibalc** [iiasa/xl2gdx#1]
The script doesn't read a table entry 0. When I read this table from the xlsx file, only the first 6 rows are read. Converting a 0 to a nonzero number changes this behavior.

	HRP	HUP	HRR	HUR	FIRM
frisch	-1.5	-1.5	-1.5	-1.5	
AGR	0.7	0.7	0.7	0.7	
FOOD	1.1	1.1	1.1	1.1	
OTHIND	1.1	1.1	1.1	1.1	
SER	1.05	1.05	1.05	1.05	
ADM	1.05	1.05	1.05	1.05	
sh0O	0	0	0	0	
tr0O	0	0	0	0	
ttdh0O	0	0	0	0	
ttdf0O					0

This the same as the issue discussed in [Example 4 - Reading a GDX File](https://www.gams.com/40/docs/UG_GDX.html#UG_GDX_READ_EXAMPLE_4) . 
The [squeeze](https://www.gams.com/40/docs/T_GDXXRW.html#GDXXRW_OPTIONS_SQUEEZE) option takes care of this in gdxxrw.

**Comment by shoibalc** [comment]
Found the fix. 
Replace  in line 772 of xl2gdx.R 
wgdx.lst(gdx_file, out_list)  -> wgdx.lst(gdx_file, out_list, squeeze="y")
Can add squeeze as a symbol attribute option.

**Comment by acjbrouwer** [comment]
I took your sample data and created a test out of it (see `test24` in the test repository). As you can see from the test, **xl2gdx** replicates the default squeezing behavior of **gdxxrw**, dropping the zeroes and empty fields. This default behavior (global option `squeeze=Y`) of **gdxrrw** is [documented here](https://www.gams.com/40/docs/T_GDXXRW.html#GDXXRW_OPTIONS_SQUEEZE) under the heading "Reading a spreadsheet: ".

So it is not a bug since the mission of **xl2gdx** is to replicate the behavior of **gdxrrw** whenever identical options are used.  But not all options are supported, for example only [this subset of the global options](https://github.com/iiasa/xl2gdx#global-options-provide-these-first) is supported, which does not include `squeeze`. I will therefore consider this to be a feature request for adding the `squeeze` global option.

**Comment by acjbrouwer** [comment]
Commit 7ec139b09317add989fb4fe01922db1284d6265f implements the `squeeze` global option. The test repo has an additional `test25` that tests the `squeeze=N` case.

Thanks for pointing out the missing functionality.
